version: '2'

networks:
  faulty-cat:

services:
    server:
        build: server
        ports:
            - "4242"
        expose:
            - "4242"
        hostname: server
        networks:
            - faulty-cat

    client:
        build: client
        networks:
            - faulty-cat
