version: '2'

networks:
  faulty-cat:

services:
    server:
        build: server
        ports:
            - "4242"
        expose:
            - "4242"
        hostname: server
        networks:
            - faulty-cat
        pid: host

    client:
        build: client
        networks:
            - faulty-cat

    gremlins:
        image: qualimente/gremlins
        volumes:
            - ./server/gremlins/profiles:/app/gremlins/profiles
        command: gremlins -m gremlins.profiles.faulty_cat -p faulty_cat.profile
        network_mode: "service:server"
        pid: host
        cap_add:
            - NET_ADMIN

